"""empty message

Revision ID: 5aa28adaf212
Revises: 220838e1842f
Create Date: 2019-03-06 13:23:27.036039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa28adaf212'
down_revision = '220838e1842f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('companies', sa.Column('portfolio_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'companies', 'portfolios', ['portfolio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'portfolio_id')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
