"""empty message

Revision ID: 6cd356f29e22
Revises: f3002e53afd8
Create Date: 2019-03-07 16:15:23.339928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd356f29e22'
down_revision = 'f3002e53afd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_companies_name', table_name='companies')
    op.drop_column('companies', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_companies_name', 'companies', ['name'], unique=True)
    # ### end Alembic commands ###
